name: "List Contributors Simple"
description: "Action to write a plain-text list of contributors login IDs to a file."
author: "@nightblade"

branding:
  icon: "users"
  color: "blue"

inputs:
  repo_names:
    description: "A list of one or more repo names (use workflowpipe syntax)."
    required: true

  output_file:
    description: "Name of the output file."
    required: true

  access_token:
    description: "GitHub token."
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
      working-directory: "${{github.action_path}}"

    - run: python3 main.py
      shell: bash
      working-directory: "${{github.action_path}}"
      env:
        INPUT_REPO_NAMES: "${{inputs.repo_names}}"
        INPUT_OUTPUT_FILE: "${{inputs.output_file}}"
        INPUT_ACCESS_TOKEN: "${{inputs.access_token}}"
