name: "List Contributors Simple"
description: "GitHub Action to write a plain-text list of contributors to a file."
author: "Nightblade"

branding:
  icon: "users"
  color: "blue"

inputs:
  repo_name:
    description: "Name of the repo: [user_name|org_name]/repo_name"
    required: true

  filename:
    description: "Output file name"
    required: true

  access_token:
    description: "Github Access Token. (Just pass GITHUB_TOKEN)"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
