name: "List Contributors Simple"
description: "GitHub Action to write a plain-text list of contributors to a file."
author: "@nightblade"

branding:
  icon: "users"
  color: "blue"

inputs:
  repo_name:
    description: "Name of the repo: [user|org]/repo"
    required: true

  filename:
    description: "Output file name"
    required: true

  access_token:
    description: "Github Access Token. (Just pass GITHUB_TOKEN)"
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
        - run: python3 main.py
          env:
            INPUT_REPO_NAME: "${{inputs.repo_name}}"
            INPUT_FILENAME: "${{inputs.filename}}"
            INPUT_ACCESS_TOKEN: "${{inputs.access_token}}"
      shell: bash
