name: Continuous Integration

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - run: python main.py
        env:
          INPUT_REPO_NAMES: "${{github.repository}}"
          INPUT_OUTPUT_FILE: "contributors.txt"
          INPUT_ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: cat contributors.txt
