name: Example usage

on:
  workflow_dispatch:

permissions: read-all

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: nightblade/list-contributors-simple@v1
        with:
          repo_name: "nightblade/list-contributors-simple"
          filename: "contributors.txt"
          access_token: ${{secrets.GITHUB_TOKEN}}
      - run: cat contributors.txt
