name: Experiment

on:
  workflow_dispatch:

permissions: read-all

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: nightblade/list-contributors-simple@dev
        with:
          repo_names: |
            PathOfBuildingCommunity/PathOfBuilding
            PathOfBuildingCommunity/PathOfBuilding-PoE2
          output_file: "contributors.txt"
          access_token: ${{secrets.GITHUB_TOKEN}}

      - run: |
          export LC_ALL=C && sort -fu contributors.txt | grep -v "github-actions" > contribs-dict.txt
          wc -l contribs-dict.txt
