name: Test missing input
on:
  workflow_dispatch:

permissions: read-all

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: nightblade/list-contributors-simple@main
      - run: cat contributors.txt
        with:
          repo_name: "PathOfBuildingCommunity/PathOfBuilding"
