name: Experiment

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: nightblade/list-contributors-simple@main
        with:
          repo_name: |
            "PathOfBuildingCommunity/PathOfBuilding"
            "PathOfBuildingCommunity/PathOfBuilding-PoE2"
          filename: |
            "contributors1.txt"
            "contributors2.txt"
          access_token: ${{secrets.GITHUB_TOKEN}}
      - run: |
          cat contributors1.txt
          cat contributors2.txt
