name: CodeQL analysis

on:
  workflow_dispatch:

permissions:
  actions: read
  security-events: write

jobs:
  codeql-analysis-call:
    name: CodeQL analysis
    uses: actions/reusable-workflows/.github/workflows/codeql-analysis.yml@main
