name: CodeQL analysis

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  codeql-analysis-call:
    name: CodeQL analysis
    uses: actions/reusable-workflows/.github/workflows/codeql-analysis.yml@main
