name: Lint

on:
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

  permissions:
    contents: read
    packages: read
    statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
