on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: nightblade/list-contributors-simple@main
        with:
          repo_name: "peter-evans/create-pull-request"
          filename: "contributors.txt"
          access_token: ${{secrets.GITHUB_TOKEN}}
      - run: cat contributors.txt
